/**
 * js/apps/firefox/pages-library.js — the browser's own library pages, split out
 * of `pages.js` to keep both files a readable size.
 *
 *   about:about         index of the pages below
 *   about:preferences   Firefox Settings, including the Live web / AI switch
 *   about:history       history library (Ctrl+H)
 *   about:bookmarks     bookmark library
 *
 * Same rules as `pages.js`: everything is rendered locally, and every value
 * that originates outside this file — URLs, page titles, typed queries — is
 * inserted through `h({ text })`, i.e. `textContent`. `innerHTML` is never used.
 *
 * The dependency runs one way, `pages-library.js` -> `pages.js`, so there is no
 * import cycle: `pages.js` knows nothing about this module.
 */

import { h } from '../../core/dom.js';
import {
  HOME_URL,
  NEWTAB_URL,
  BLANK_URL,
  PREFS_URL,
  HISTORY_URL,
  BOOKMARKS_URL,
  ABOUT_URL,
  MODE_LIVE,
  MODE_AI,
  fxIcon,
  faviconChip,
  button,
  prettyUrl,
  clockText,
  dayLabel,
  renderStartPage,
  renderBlankPage,
} from './pages.js';

/** Title shown in the tab strip for each local page. */
const LOCAL_TITLES = {
  [HOME_URL]: 'Ubuntu Start',
  [NEWTAB_URL]: 'New Tab',
  [BLANK_URL]: 'about:blank',
  [PREFS_URL]: 'Settings',
  [HISTORY_URL]: 'History',
  [BOOKMARKS_URL]: 'Bookmarks',
  [ABOUT_URL]: 'About About',
};

/* ------------------------------------------------------ shared pieces --- */

/**
 * Section wrapper used by the pages in this module.
 * @param {string} title
 * @param {...any} children
 * @returns {HTMLElement}
 */
function panel(title, ...children) {
  return h('section.fx-panel', {}, h('h2.fx-panel-title', { text: title }), ...children);
}

/**
 * Empty-state block.
 * @param {string} iconName
 * @param {string} title
 * @param {string} body
 * @returns {HTMLElement}
 */
function emptyState(iconName, title, body) {
  return h(
    'div.fx-empty',
    {},
    fxIcon(iconName, 30, { class: 'fx-empty-icon' }),
    h('p.fx-empty-title', { text: title }),
    h('p.fx-empty-body', { text: body })
  );
}

/* --------------------------------------------------------- about:about -- */

/**
 * about:about — index of the pages this browser implements locally.
 * @param {object} browser
 * @returns {HTMLElement}
 */
export function renderAboutIndexPage(browser) {
  const rows = [
    { url: HOME_URL, note: 'Ubuntu Start page' },
    { url: NEWTAB_URL, note: 'New tab page' },
    { url: BLANK_URL, note: 'Empty document' },
    { url: PREFS_URL, note: 'Browser settings' },
    { url: HISTORY_URL, note: 'Browsing history' },
    { url: BOOKMARKS_URL, note: 'Saved bookmarks' },
    { url: ABOUT_URL, note: 'This page' },
  ];
  const list = h('ul.fx-about-list');
  for (const row of rows) {
    list.appendChild(
      h(
        'li.fx-about-item',
        {},
        h('button.fx-link', { type: 'button', text: row.url, on: { click: () => browser.navigate(row.url) } }),
        h('span.fx-about-note', { text: row.note })
      )
    );
  }
  return h(
    'div.fx-page.fx-about-page',
    {},
    h('h1.fx-page-title', { text: 'List of about: pages' }),
    h('p.fx-page-lede', { text: 'These pages are part of the browser itself. They are rendered locally and never generated by AI.' }),
    list
  );
}

/* ---------------------------------------------------- about:preferences -- */

function prefRow(label, description, control) {
  return h(
    'div.fx-pref-row',
    {},
    h(
      'div.fx-pref-labels',
      {},
      h('div.fx-pref-label', { text: label }),
      description ? h('div.fx-pref-desc', { text: description }) : null
    ),
    h('div.fx-pref-control', {}, control)
  );
}

function checkbox(checked, onChange, label) {
  const input = h('input.fx-checkbox', { type: 'checkbox', checked: !!checked });
  input.addEventListener('change', () => onChange(input.checked));
  return h('label.fx-checkbox-wrap', {}, input, h('span', { text: label }));
}

function selectField(options, value, onChange) {
  const sel = h('select.fx-select');
  for (const opt of options) sel.appendChild(h('option', { value: opt.value, text: opt.label }));
  sel.value = value;
  sel.addEventListener('change', () => onChange(sel.value));
  return sel;
}

/**
 * about:preferences — a working Firefox Settings page. Every control writes
 * through `browser.setPref` and takes effect immediately.
 * @param {object} browser
 * @returns {HTMLElement}
 */
export function renderPreferencesPage(browser) {
  const page = h('div.fx-page.fx-prefs');
  const body = h('div.fx-prefs-body');

  const build = () => {
    const prefs = browser.prefs();
    const live = browser.mode() === MODE_LIVE;
    while (body.firstChild) body.removeChild(body.firstChild);

    /* --- Browsing mode ------------------------------------------------- */
    body.appendChild(
      panel(
        'Browsing mode',
        prefRow(
          'How pages are loaded',
          live
            ? 'Live web really fetches the address in a sandboxed frame. Sites that refuse to be framed get an interstitial, never a fake page.'
            : 'AI simulation asks Gemini to write the content of the address you typed. Nothing is fetched from the site.',
          selectField(
            [
              { value: MODE_LIVE, label: 'Live web (real network)' },
              { value: MODE_AI, label: 'AI simulation (Gemini)' },
            ],
            live ? MODE_LIVE : MODE_AI,
            (value) => {
              browser.setMode(value);
              build();
            }
          )
        )
      )
    );

    /* --- General ------------------------------------------------------- */
    const homeOptions = [
      { value: HOME_URL, label: 'Ubuntu Start (default)' },
      { value: BLANK_URL, label: 'Blank Page' },
      { value: 'custom', label: 'Custom URL…' },
    ];
    const isCustom = prefs.homepage !== HOME_URL && prefs.homepage !== BLANK_URL;
    const customInput = h('input.fx-input', {
      type: 'text',
      value: isCustom ? prefs.homepage : prefs.customHome || '',
      placeholder: 'https://ubuntu.com/',
      'aria-label': 'Custom home page address',
    });
    customInput.addEventListener('change', () => {
      const value = customInput.value.trim();
      browser.setPref('customHome', value);
      if (value !== '') browser.setPref('homepage', value);
    });
    const customRow = prefRow('Custom home page', 'Used when “Custom URL…” is selected above.', customInput);
    customRow.hidden = !isCustom;

    body.appendChild(
      panel(
        'Home',
        prefRow(
          'Homepage and new windows',
          'Shown when you press the Home button or open a new window.',
          selectField(homeOptions, isCustom ? 'custom' : prefs.homepage, (value) => {
            if (value === 'custom') {
              const custom = (prefs.customHome || '').trim();
              browser.setPref('homepage', custom !== '' ? custom : HOME_URL);
            } else {
              browser.setPref('homepage', value);
            }
            build();
          })
        ),
        customRow,
        prefRow(
          'Startup',
          null,
          checkbox(prefs.restoreSession, (v) => browser.setPref('restoreSession', v), 'Open previous windows and tabs')
        ),
        prefRow(
          'Tabs',
          null,
          checkbox(prefs.warnOnQuit, (v) => browser.setPref('warnOnQuit', v), 'Confirm before closing multiple tabs')
        )
      )
    );

    /* --- Search -------------------------------------------------------- */
    body.appendChild(
      panel(
        'Search',
        prefRow(
          'Default search engine',
          live
            ? 'Real results from the DuckDuckGo Instant Answer API and the Wikipedia search API — the two engines that allow cross-origin requests without a key.'
            : 'Queries are answered by Google Gemini using your own API key.',
          h('div.fx-pref-static', { text: live ? 'DuckDuckGo + Wikipedia' : 'Gemini (simulated)' })
        ),
        prefRow(
          'Address bar',
          null,
          checkbox(prefs.acSuggest, (v) => browser.setPref('acSuggest', v), 'Suggest browsing history and bookmarks')
        ),
        prefRow(
          'API key',
          'Stored only in this browser profile. Nothing is sent anywhere else.',
          button('Open AI Configuration', () => browser.openAiSettings(), { icon: 'key' })
        )
      )
    );

    /* --- Reader -------------------------------------------------------- */
    const sizeInput = h('input.fx-range', {
      type: 'range',
      min: '14',
      max: '26',
      step: '1',
      value: String(prefs.readerFontSize),
      'aria-label': 'Reader font size',
    });
    const sizeValue = h('span.fx-range-value', { text: `${prefs.readerFontSize} px` });
    sizeInput.addEventListener('input', () => {
      const value = Number(sizeInput.value);
      sizeValue.textContent = `${value} px`;
      browser.setPref('readerFontSize', value);
    });

    body.appendChild(
      panel(
        'Reader View',
        prefRow('Font size', 'Applies to pages opened in Reader View.', h('div.fx-range-wrap', {}, sizeInput, sizeValue)),
        prefRow(
          'Colour scheme',
          null,
          selectField(
            [
              { value: 'light', label: 'Light' },
              { value: 'sepia', label: 'Sepia' },
            ],
            prefs.readerTheme,
            (v) => browser.setPref('readerTheme', v)
          )
        )
      )
    );

    /* --- Privacy ------------------------------------------------------- */
    const historyCount = browser.history().length;
    const bookmarkCount = browser.bookmarks().length;
    body.appendChild(
      panel(
        'Privacy & Security',
        prefRow(
          'Browsing history',
          `${historyCount} ${historyCount === 1 ? 'entry' : 'entries'} stored in this profile.`,
          button('Clear History…', () => {
            browser.clearHistory().then((done) => {
              if (done) build();
            });
          }, { icon: 'trash', variant: 'danger' })
        ),
        prefRow(
          'Bookmarks',
          `${bookmarkCount} ${bookmarkCount === 1 ? 'bookmark' : 'bookmarks'} stored in this profile.`,
          button('Remove All Bookmarks…', () => {
            browser.clearBookmarks().then((done) => {
              if (done) build();
            });
          }, { icon: 'trash', variant: 'danger' })
        ),
        prefRow(
          'Network',
          null,
          h('div.fx-pref-static', {
            text: live
              ? 'In Live web mode the pages you open are fetched by the real browser, so the sites you visit see this machine exactly as any other visit. Frames are sandboxed and are never scripted by this app.'
              : 'In AI simulation mode this browser never contacts a website. The only outbound request is to the Gemini API when you search or open a page.',
          })
        )
      )
    );
  };

  build();
  page.appendChild(h('h1.fx-page-title', { text: 'Settings' }));
  page.appendChild(body);
  return page;
}

/* -------------------------------------------------------- about:history -- */

/**
 * Shared list renderer for the two library pages.
 * @param {object[]} entries
 * @param {object} browser
 * @param {{grouped:boolean, onForget:(entry:object)=>void, forgetLabel:string}} opts
 * @returns {HTMLElement}
 */
function libraryList(entries, browser, opts) {
  const list = h('div.fx-lib-list');
  let lastDay = '';
  for (const entry of entries) {
    if (opts.grouped) {
      const label = dayLabel(entry.ts);
      if (label !== lastDay) {
        lastDay = label;
        list.appendChild(h('div.fx-lib-day', { text: label }));
      }
    }
    const open = () => browser.navigate(entry.url);
    const row = h('div.fx-lib-row');
    row.appendChild(faviconChip(entry.url, { size: 16 }));
    row.appendChild(
      h(
        'button.fx-lib-main',
        { type: 'button', title: entry.url, on: { click: open } },
        h('span.fx-lib-title', { text: entry.title || prettyUrl(entry.url) }),
        h('span.fx-lib-url', { text: prettyUrl(entry.url) })
      )
    );
    row.appendChild(h('span.fx-lib-time', { text: clockText(entry.ts) }));
    row.appendChild(
      h('button.fx-lib-forget', {
        type: 'button',
        title: opts.forgetLabel,
        'aria-label': `${opts.forgetLabel}: ${entry.title || entry.url}`,
        on: { click: () => opts.onForget(entry) },
      }, fxIcon('close', 14))
    );
    list.appendChild(row);
  }
  return list;
}

/**
 * Build a library page (history / bookmarks) with a live filter field.
 * @param {object} browser
 * @param {{title:string, placeholder:string, grouped:boolean, source:()=>object[],
 *          onForget:(entry:object)=>void, forgetLabel:string, actions?:HTMLElement[],
 *          empty:[string,string,string]}} spec
 * @returns {HTMLElement}
 */
function libraryPage(browser, spec) {
  const page = h('div.fx-page.fx-library');
  const host = h('div.fx-lib-host');
  const filter = h('input.fx-input.fx-lib-filter', {
    type: 'text',
    placeholder: spec.placeholder,
    'aria-label': spec.placeholder,
    autocomplete: 'off',
    spellcheck: 'false',
  });

  const refresh = () => {
    const needle = filter.value.trim().toLowerCase();
    const entries = spec.source().filter((entry) => {
      if (needle === '') return true;
      return `${entry.title || ''} ${entry.url || ''}`.toLowerCase().includes(needle);
    });
    while (host.firstChild) host.removeChild(host.firstChild);
    if (entries.length === 0) {
      host.appendChild(emptyState(spec.empty[0], spec.empty[1], needle === '' ? spec.empty[2] : `No results for “${needle}”.`));
      return;
    }
    host.appendChild(
      libraryList(entries, browser, {
        grouped: spec.grouped,
        forgetLabel: spec.forgetLabel,
        onForget: (entry) => {
          spec.onForget(entry);
          refresh();
        },
      })
    );
  };

  filter.addEventListener('input', refresh);

  const bar = h('div.fx-lib-bar', {}, h('h1.fx-page-title', { text: spec.title }), h('div.fx-lib-tools', {}, filter, ...(spec.actions || [])));
  page.appendChild(bar);
  page.appendChild(host);
  refresh();
  page.refresh = refresh;
  return page;
}

/**
 * about:history — Ctrl+H.
 * @param {object} browser
 * @returns {HTMLElement}
 */
export function renderHistoryPage(browser) {
  let page = null;
  const clearBtn = button(
    'Clear all history…',
    () => {
      browser.clearHistory().then((done) => {
        if (done && page) page.refresh();
      });
    },
    { icon: 'trash', variant: 'danger' }
  );
  page = libraryPage(browser, {
    title: 'History',
    placeholder: 'Search history',
    grouped: true,
    forgetLabel: 'Forget this page',
    source: () => browser.history(),
    onForget: (entry) => browser.forgetHistory(entry.url),
    actions: [clearBtn],
    empty: ['clock', 'No history yet', 'Pages you visit in this browser are listed here.'],
  });
  return page;
}

/**
 * about:bookmarks.
 * @param {object} browser
 * @returns {HTMLElement}
 */
export function renderBookmarksPage(browser) {
  let page = null;
  const clearBtn = button(
    'Remove all…',
    () => {
      browser.clearBookmarks().then((done) => {
        if (done && page) page.refresh();
      });
    },
    { icon: 'trash', variant: 'danger' }
  );
  page = libraryPage(browser, {
    title: 'Bookmarks',
    placeholder: 'Search bookmarks',
    grouped: false,
    forgetLabel: 'Remove bookmark',
    source: () => browser.bookmarks(),
    onForget: (entry) => browser.removeBookmark(entry.url),
    actions: [clearBtn],
    empty: ['star', 'No bookmarks yet', 'Press the star in the address bar, or Ctrl+D, to save the page you are on.'],
  });
  return page;
}

/* --------------------------------------------------------- dispatcher --- */

/**
 * @param {string} url
 * @returns {boolean} true for a page implemented in this module
 */
export function isLocalUrl(url) {
  const key = String(url || '').trim().toLowerCase();
  return Object.prototype.hasOwnProperty.call(LOCAL_TITLES, key);
}

/**
 * Tab title for a local page.
 * @param {string} url
 * @returns {string}
 */
export function titleForLocal(url) {
  const key = String(url || '').trim().toLowerCase();
  return LOCAL_TITLES[key] || key;
}

/**
 * Render one of the local pages.
 * @param {string} url
 * @param {object} browser
 * @returns {HTMLElement|null} null when `url` is not a local page
 */
export function renderLocalPage(url, browser) {
  switch (String(url || '').trim().toLowerCase()) {
    case HOME_URL:
    case NEWTAB_URL:
      return renderStartPage(browser);
    case BLANK_URL:
      return renderBlankPage();
    case PREFS_URL:
      return renderPreferencesPage(browser);
    case HISTORY_URL:
      return renderHistoryPage(browser);
    case BOOKMARKS_URL:
      return renderBookmarksPage(browser);
    case ABOUT_URL:
      return renderAboutIndexPage(browser);
    default:
      return null;
  }
}
